from dotenv import load_dotenv
import os

load_dotenv()

print("GOOGLE_API_KEY =", os.getenv("GOOGLE_API_KEY"))

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate
import os

# Load environment variables
load_dotenv()

# Initialize Gemini LLM
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    google_api_key=os.getenv("GOOGLE_API_KEY"),
    temperature=0.3,
)

# Prompt Template
phishing_prompt = ChatPromptTemplate.from_template("""
You are an expert Cybersecurity SOC Analyst.

A Machine Learning model has classified the following email as PHISHING.

Prediction:
{prediction}

Sender:
{sender}

Subject:
{subject}

Contains Links:
{has_links}

Contains Attachments:
{has_attachments}

Email Content:
{email}

Generate a professional cybersecurity threat report.

Use the following format exactly.

# 🔒 AI Email Threat Analysis

## Threat Level

High

## Threat Type

Choose ONLY one:

- Credential Phishing
- Business Email Compromise
- Financial Scam
- Malware Delivery
- Social Engineering
- Unknown

## Confidence

High / Medium / Low

## Detected Security Indicators

Only explain indicators that are directly visible in the supplied information.

Do not invent indicators.

If there is insufficient evidence for an indicator, state:

"Not enough evidence to determine."

## Technical Reasoning

Explain why the email may have been classified as phishing.

If the ML prediction appears to rely on information not visible in the email, clearly state that.

## Potential Impact

Only describe realistic impacts supported by the supplied information.

## Recommended Actions

Provide five practical recommendations.

## Executive Summary

Summarize the assessment in 2–3 concise sentences.

Important Rules

- Never invent evidence.
- Never assume spoofing.
- Never assume hidden malicious links.
- Never assume malware.
- Never claim certainty when evidence is unavailable.
- Base every statement only on the supplied email and metadata.
- Keep the report concise and professional.
""")

incident_report_prompt = ChatPromptTemplate.from_template("""
You are a Senior SOC (Security Operations Center) Incident Response Analyst.

Generate a professional cybersecurity incident report.

Incident ID:
{incident_id}

Generated On:
{generated_time}

Analysis Type:
{analysis_type}

Threat Level:
{threat_level}

Threat Classification:
{threat_type}

Risk Score:
{risk_score}

AI Analysis:
{analysis}

Generate the report in the following professional format.

══════════════════════════════════════════════════════════════
               AI CYBERSHIELD INCIDENT REPORT
══════════════════════════════════════════════════════════════

Incident ID      : {incident_id}

Generated On     : {generated_time}

Generated By     : AI CyberShield Intelligence Engine

Analysis Type    : {analysis_type}

Threat Level     : {threat_level}

Threat Status    : ACTIVE

══════════════════════════════════════════════════════════════
EXECUTIVE SUMMARY
══════════════════════════════════════════════════════════════

Write a concise executive summary (3–5 lines) explaining the incident.

══════════════════════════════════════════════════════════════
TECHNICAL ANALYSIS
══════════════════════════════════════════════════════════════

Threat Classification
---------------------

{threat_type}

Detailed Findings
-----------------

Summarize the important technical findings from the AI analysis.

══════════════════════════════════════════════════════════════
RISK ASSESSMENT
══════════════════════════════════════════════════════════════

Overall Risk
------------

{threat_level}

Business Impact
---------------

Explain the possible impact based on the supplied analysis.

Severity
--------

Choose one:
- Critical
- High
- Medium
- Low

Likelihood
----------

Choose one:
- High
- Medium
- Low

══════════════════════════════════════════════════════════════
RECOMMENDED MITIGATION
══════════════════════════════════════════════════════════════

Provide five practical mitigation steps.

══════════════════════════════════════════════════════════════
INCIDENT STATUS
══════════════════════════════════════════════════════════════

Current Status
--------------

Choose:
- Open
- Under Investigation
- Closed

Recommended Priority
--------------------

Choose:
- P1
- P2
- P3
- P4

══════════════════════════════════════════════════════════════
END OF REPORT
══════════════════════════════════════════════════════════════

Generated by AI CyberShield
Powered by Machine Learning + Google Gemini AI

Rules:

- Keep the report professional.
- Do not invent evidence.
- Base every section only on the supplied AI analysis.
- Do not repeat the same information.
- Use concise SOC-style language.
""")

legitimate_prompt = ChatPromptTemplate.from_template("""
You are an expert Cybersecurity SOC Analyst.

A Machine Learning model has classified the following email as LEGITIMATE.

Prediction:
{prediction}

Sender:
{sender}

Subject:
{subject}

Contains Links:
{has_links}

Contains Attachments:
{has_attachments}

Email Content:
{email}

Generate a professional email security assessment.

The objective is to explain why the email appears safe.

Use the following format exactly.

# ✅ AI Email Security Assessment

## Security Status

Legitimate

## Email Assessment

Explain why the email appears legitimate.

## Positive Security Indicators

Only mention indicators actually visible.

Examples include:

- Professional language
- Personalized greeting
- Trusted sender
- Expected communication
- Proper formatting
- No urgency tactics
- No credential request
- No suspicious wording

Only include indicators that are actually present.

## Good Security Practices

Provide 3–5 general cybersecurity recommendations.

Examples:

- Verify unexpected emails before responding.
- Keep Multi-Factor Authentication enabled.
- Keep antivirus software updated.
- Be cautious with unexpected attachments.
- Verify sensitive requests through trusted channels.

## Executive Summary

Summarize why the email appears legitimate in 2–3 concise sentences.

Important Rules

- Never generate Threat Level.
- Never generate Threat Type.
- Never mention phishing.
- Never mention malware.
- Never mention credential theft.
- Never speculate.
- Never invent suspicious indicators.
- Base every statement only on the supplied information.
- Keep the response concise and professional.
""")
# Create analysis chain


def generate_threat_analysis(
    email_text: str,
    prediction: str,
    sender: str = "Unknown",
    subject: str = "Unknown",
    has_links: str = "Unknown",
    has_attachments: str = "Unknown",
) -> str:
    """
    Generates a structured AI cybersecurity report
    using ML prediction and extracted email metadata.
    """

    try:

        if prediction.lower() == "phishing":
            chain = phishing_prompt | llm
        else:
            chain = legitimate_prompt | llm

        response = chain.invoke(
            {
                "prediction": prediction,
                "sender": sender,
                "subject": subject,
                "has_links": has_links,
                "has_attachments": has_attachments,
                "email": email_text,
            }
        )

        return response.content

    except Exception as e:
        return f"""
# ❌ AI Analysis Error

The AI Threat Analysis Engine could not generate a report.

**Reason:**
{str(e)}

Please verify:
- GOOGLE_API_KEY is configured correctly.
- Internet connection is available.
- Gemini API quota has not been exceeded.
"""
    
def generate_website_analysis(url, risk_score, indicators, verdict):
    """
    Generates an AI-powered website security analysis.
    """

    website_prompt = ChatPromptTemplate.from_template("""
You are an expert Cybersecurity Web Security Analyst.

A heuristic phishing detection engine has already analyzed a website.

Website URL:
{url}

Risk Score:
{risk_score}/100

Verdict:
{verdict}

Detected Indicators:
{indicators}

Your task is to generate a professional cybersecurity assessment based ONLY on the information provided.

Never invent facts.
Never speculate about hypothetical situations.
Do not assume indicators that are not provided.
Base every conclusion only on the supplied URL, heuristic score and detected indicators.

----------------------------------------
IF Verdict = HIGH RISK
----------------------------------------

Generate the report using this format exactly:

# 🌐 AI Website Threat Analysis

## Threat Level

(High)

## Website Assessment

Briefly explain why the website is considered suspicious.

## Detected Security Indicators

Explain each detected indicator in simple language.

## URL Structure Analysis

Discuss only the characteristics actually detected, such as:
- HTTPS usage
- Domain structure
- Suspicious keywords
- Hyphens
- URL length
- Subdomains
- Brand impersonation

Do not mention indicators that are not present.

## Potential Risks

Explain realistic risks such as:
- Credential theft
- Fake login pages
- Malware delivery
- Financial fraud

Only include risks supported by the detected indicators.

## Recommended Actions

Provide 5 practical security recommendations.

## Executive Summary

Summarize the overall assessment in 2–3 concise sentences.

----------------------------------------
IF Verdict = LOW RISK
----------------------------------------

Generate the report using this format exactly:

# 🌐 AI Website Security Assessment

## Security Status

(Low Risk)

## Website Assessment

Explain why the website appears safe based on the heuristic analysis.

## Positive Security Indicators

List only the positive indicators actually observed.

Examples include:
- HTTPS enabled
- Clean domain structure
- No suspicious keywords
- Normal URL length
- No excessive subdomains

Only mention those that are actually supported by the heuristic analysis.

## Good Security Practices

Provide 3–5 general cybersecurity tips for safely browsing legitimate websites.

## Executive Summary

Summarize why the website currently appears safe.

----------------------------------------
Important Rules
----------------------------------------

- Never generate hypothetical attack scenarios.
- Never mention malware, credential theft or phishing risks for LOW RISK websites.
- Never include sections that do not belong to the selected report type.
- Keep the response concise, professional and suitable for a cybersecurity dashboard.
""")
    
    website_chain = website_prompt | llm

    try:
        response = website_chain.invoke({
            "url": url,
            "risk_score": risk_score,
            "verdict": verdict,
            "indicators": ", ".join(indicators) if indicators else "None"
        })

        return response.content

    except Exception as e:
        return f"""
# ❌ AI Website Analysis Error

**Reason:**
{str(e)}
"""

print("generate_website_analysis loaded")

from datetime import datetime
import uuid


def generate_incident_report(
    analysis,
    analysis_type,
    threat_level,
    threat_type,
    risk_score,
):
    incident_chain = incident_report_prompt | llm

    incident_id = (
        f"CS-{datetime.now().strftime('%Y%m%d')}-"
        f"{str(uuid.uuid4())[:8].upper()}"
    )

    generated_time = datetime.now().strftime("%d %B %Y %I:%M %p")

    try:

        response = incident_chain.invoke(
            {
                "incident_id": incident_id,
                "generated_time": generated_time,
                "analysis_type": analysis_type,
                "threat_level": threat_level,
                "threat_type": threat_type,
                "risk_score": risk_score,
                "analysis": analysis,
            }
        )

        return response.content

    except Exception as e:
        print("Incident Report Error:", e)
        raise