from datetime import datetime
import re
import uuid

from src.security_core import severity_from_score


def generate_incident_report(
    analysis: str,
    analysis_type: str,
    threat_level: str,
    threat_type: str,
    risk_score: str,
    analyst_notes: str = "",
):
    """
    Generates a professional Security Incident Report
    without making another AI request.
    """

    incident_id = (
        f"CS-{datetime.now().strftime('%Y%m%d')}-"
        f"{str(uuid.uuid4())[:8].upper()}"
    )

    generated_time = datetime.now().strftime("%d %B %Y | %I:%M %p")

    # -----------------------------------------
    # Normalize Threat Information
    # -----------------------------------------

    # Risk score is the single source of truth for SOC severity.
    score_match = re.search(r"[0-9]+(?:\.[0-9]+)?", str(risk_score or "0"))
    score = float(score_match.group()) if score_match else 0.0
    severity, priority_code = severity_from_score(score)

    level = threat_level.lower().strip()
    if "email" in analysis_type.lower():
        display_type = "Credential Phishing" if level == "phishing" else "Legitimate Communication"
    elif "domain" in analysis_type.lower() or "website" in analysis_type.lower():
        display_type = "Malicious Website" if level in {"high risk", "suspicious", "suspicious website"} else "Legitimate Website"
    else:
        display_type = threat_type

    priority_labels = {
        "CRITICAL": "P1 - Immediate Investigation",
        "HIGH": "P2 - Priority Investigation",
        "MEDIUM": "P3 - Analyst Review",
        "LOW": "P4 - No Immediate Action",
    }
    priority = priority_labels[severity]
    incident_status = "Closed" if severity == "LOW" else "Open"

    report = f"""
# 🛡️ AI CYBERSHIELD SECURITY INCIDENT REPORT

---

# Incident Information

| Field | Value |
| :--- | :--- |
| **Incident ID** | {incident_id} |
| **Generated On** | {generated_time} |
| **Generated By** | AI CyberShield Intelligence Engine |
| **Analysis Type** | {analysis_type} |
| **Threat Level** | **{severity}** |
| **Threat Classification** | **{display_type}** |
| **Risk Score** | **{score:g}/100** |
| **Incident Status** | **{incident_status}** |

---

# Executive Summary

This report was automatically generated by the AI CyberShield platform after completing a Machine Learning and AI-assisted cybersecurity analysis.

The findings below summarize the observed security indicators, technical assessment, and recommended mitigation actions.

---

# Technical Findings

{analysis}

---

# Risk Assessment

| Category | Status |
| :--- | :--- |
| **Threat Level** | {severity} |
| **Risk Score** | {score:g}/100 |
| **Incident Status** | {incident_status} |
| **Priority** | {priority} |

---

# Recommended Next Steps

- Review the AI findings carefully.
- Validate all identified security indicators.
- Follow the recommended mitigation actions.
- Document the incident within the security management system.
- Escalate to the Security Operations Center (SOC) if required.

---

# Analyst Notes

{analyst_notes or "No analyst notes recorded."}

---

# Report Metadata

| Item | Value |
| :--- | :--- |
| Platform | AI CyberShield |
| Detection Engine | Machine Learning + Google Gemini AI |
| Report Version | 2.0 |
| Generated | {generated_time} |

---

**End of Security Incident Report**
"""

    return report

def update_incident_report_content(report, *, status=None, analyst_notes=None):
    """Update mutable report sections while preserving the original findings."""
    text = str(report or "")

    if status is not None:
        text = re.sub(
            r"(\|\s*\*\*Incident Status\*\*\s*\|\s*)\*\*[^|]*?\*\*(\s*\|)",
            lambda m: m.group(1) + f"**{status}**" + m.group(2),
            text,
        )

    if analyst_notes is not None:
        notes = analyst_notes.strip() or "No analyst notes recorded."
        pattern = r"(# Analyst Notes\s*\n\n)(.*?)(\n\n---\n\n# Report Metadata)"
        text, count = re.subn(
            pattern,
            lambda m: m.group(1) + notes + m.group(3),
            text,
            count=1,
            flags=re.S,
        )
        if count == 0:
            text += f"\n\n---\n\n# Analyst Notes\n\n{notes}\n"

    return text
