from datetime import datetime
import uuid


def generate_incident_report(
    analysis: str,
    analysis_type: str,
    threat_level: str,
    threat_type: str,
    risk_score: str,
):
    """
    Generates a professional Security Incident Report
    without making another AI request.
    """

    incident_id = (
        f"CS-{datetime.now().strftime('%Y%m%d')}-"
        f"{str(uuid.uuid4())[:8].upper()}"
    )

    generated_time = datetime.now().strftime("%d %B %Y | %I:%M %p")

    # -----------------------------------------
    # Normalize Threat Information
    # -----------------------------------------

    level = threat_level.lower().strip()

    if level == "phishing":
        display_level = "High"
        display_type = "Credential Phishing"
        incident_status = "Open"
        priority = "P1 - Immediate Investigation"

    elif level == "legitimate":
        display_level = "Low"
        display_type = "Legitimate Communication"
        incident_status = "Closed"
        priority = "No Action Required"

    elif level == "high risk":
        display_level = "High"
        display_type = "Malicious Website"
        incident_status = "Open"
        priority = "P1 - Immediate Investigation"

    elif level == "low risk":
        display_level = "Low"
        display_type = "Legitimate Website"
        incident_status = "Closed"
        priority = "No Action Required"

    else:
        display_level = threat_level
        display_type = threat_type
        incident_status = "Under Investigation"
        priority = "P2 - Review Required"

    report = f"""
# 🛡️ AI CYBERSHIELD SECURITY INCIDENT REPORT

---

# Incident Information

| Field | Value |
| :--- | :--- |
| **Incident ID** | {incident_id} |
| **Generated On** | {generated_time} |
| **Generated By** | AI CyberShield Intelligence Engine |
| **Analysis Type** | {analysis_type} |
| **Threat Level** | **{display_level}** |
| **Threat Classification** | **{display_type}** |
| **Risk Score** | **{risk_score}** |
| **Incident Status** | **{incident_status}** |

---

# Executive Summary

This report was automatically generated by the AI CyberShield platform after completing a Machine Learning and AI-assisted cybersecurity analysis.

The findings below summarize the observed security indicators, technical assessment, and recommended mitigation actions.

---

# Technical Findings

{analysis}

---

# Risk Assessment

| Category | Status |
| :--- | :--- |
| **Threat Level** | {display_level} |
| **Risk Score** | {risk_score} |
| **Incident Status** | {incident_status} |
| **Priority** | {priority} |

---

# Recommended Next Steps

- Review the AI findings carefully.
- Validate all identified security indicators.
- Follow the recommended mitigation actions.
- Document the incident within the security management system.
- Escalate to the Security Operations Center (SOC) if required.

---

# Report Metadata

| Item | Value |
| :--- | :--- |
| Platform | AI CyberShield |
| Detection Engine | Machine Learning + Google Gemini AI |
| Report Version | 2.0 |
| Generated | {generated_time} |

---

**End of Security Incident Report**
"""

    return report